# This is the network config written by 'subiquity'
network:
  ethernets:
    management: #eno1
      addresses:
      - 10.221.36.20/24
      nameservers:
        addresses:
        - 8.8.8.8
        - 8.8.4.4
        search: []
      routes:
      - to: default
        via: 10.221.36.1
      match:
       macaddress: 18:66:da:4f:62:7b
      set-name: management
    neutron: #eno2
      addresses:
      - 10.221.36.21/24
      nameservers:
        addresses:  
        - 8.8.8.8
        - 8.8.4.4
        search: []
      match: 
       macaddress: 18:66:da:4f:62:7d
      set-name: neutron
    eno3:
      dhcp4: true
  version: 2


                       